name: automerge
description: automerge is a dart implementation a columnar crdt as defined by Martin Kleppman
version: 0.0.1
author: Matt Ho
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi: "1.0.0"

dev_dependencies:
  test: ^1.14.2

